Using: mps
OK, elapsed: 0.002847909927368164 s 741238.375
load yaml path: configs/exp_ours.yaml
Traceback (most recent call last):
  File "/Users/yuandouwang/Documents/projects/flsim_min/flsim/run_experiment_ours.py", line 461, in <module>
    main()
  File "/Users/yuandouwang/Documents/projects/flsim_min/flsim/run_experiment_ours.py", line 196, in main
    log_file = open(f"./results/fl_log_ours_{args.mal_behavior}_{args.dataset}_{args.model}.csv", "w", newline="")
FileNotFoundError: [Errno 2] No such file or directory: './results/fl_log_ours_scale_jiahborcn/chembl_aqsol_mlp.csv'
/Users/yuandouwang/miniconda3/envs/FLSimulation/lib/python3.10/site-packages/flwr_datasets/utils.py:109: UserWarning: The currently tested dataset are ['mnist', 'ylecun/mnist', 'cifar10', 'uoft-cs/cifar10', 'fashion_mnist', 'zalando-datasets/fashion_mnist', 'sasha/dog-food', 'zh-plus/tiny-imagenet', 'scikit-learn/adult-census-income', 'cifar100', 'uoft-cs/cifar100', 'svhn', 'ufldl-stanford/svhn', 'sentiment140', 'stanfordnlp/sentiment140', 'speech_commands', 'LIUM/tedlium', 'flwrlabs/femnist', 'flwrlabs/ucf101', 'flwrlabs/ambient-acoustic-context', 'jlh/uci-mushrooms', 'Mike0307/MNIST-M', 'flwrlabs/usps', 'scikit-learn/iris', 'flwrlabs/pacs', 'flwrlabs/cinic10', 'flwrlabs/caltech101', 'flwrlabs/office-home', 'flwrlabs/fed-isic2019']. Given: jiahborcn/chembl_aqsol.
  warnings.warn(
Using: mps
OK, elapsed: 0.0029370784759521484 s 741212.3125
load yaml path: configs/exp_ours.yaml
Generating train split:   0%|          | 0/12889 [00:00<?, ? examples/s]Generating train split: 100%|██████████| 12889/12889 [00:00<00:00, 506900.06 examples/s]
Generating test split:   0%|          | 0/3223 [00:00<?, ? examples/s]Generating test split: 100%|██████████| 3223/3223 [00:00<00:00, 1586275.73 examples/s]
Traceback (most recent call last):
  File "/Users/yuandouwang/Documents/projects/flsim_min/flsim/run_experiment_ours.py", line 461, in <module>
    main()
  File "/Users/yuandouwang/Documents/projects/flsim_min/flsim/run_experiment_ours.py", line 206, in main
    Xp, yp, D, K, X_eval, y_eval = load_flower_arrays(
  File "/Users/yuandouwang/Documents/projects/flsim_min/flsim/data/flower.py", line 198, in load_flower_arrays
    ds = fds_train.load_partition(cid, split=split).with_format("numpy")
  File "/Users/yuandouwang/miniconda3/envs/FLSimulation/lib/python3.10/site-packages/flwr_datasets/federated_dataset.py", line 187, in load_partition
    partition = partitioner.load_partition(partition_id)
  File "/Users/yuandouwang/miniconda3/envs/FLSimulation/lib/python3.10/site-packages/flwr_datasets/partitioner/dirichlet_partitioner.py", line 134, in load_partition
    self._determine_partition_id_to_indices_if_needed()
  File "/Users/yuandouwang/miniconda3/envs/FLSimulation/lib/python3.10/site-packages/flwr_datasets/partitioner/dirichlet_partitioner.py", line 205, in _determine_partition_id_to_indices_if_needed
    self._unique_classes = self.dataset.unique(self._partition_by)
  File "/Users/yuandouwang/miniconda3/envs/FLSimulation/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 1850, in unique
    raise ValueError(f"Column ({column}) not in table columns ({self._data.column_names}).")
ValueError: Column (label) not in table columns (['smiles', 'logS', 'molecule_chembl_id', 'assay_description', 'MW', 'LogP', 'TPSA', 'Complexity']).
/Users/yuandouwang/miniconda3/envs/FLSimulation/lib/python3.10/site-packages/flwr_datasets/utils.py:109: UserWarning: The currently tested dataset are ['mnist', 'ylecun/mnist', 'cifar10', 'uoft-cs/cifar10', 'fashion_mnist', 'zalando-datasets/fashion_mnist', 'sasha/dog-food', 'zh-plus/tiny-imagenet', 'scikit-learn/adult-census-income', 'cifar100', 'uoft-cs/cifar100', 'svhn', 'ufldl-stanford/svhn', 'sentiment140', 'stanfordnlp/sentiment140', 'speech_commands', 'LIUM/tedlium', 'flwrlabs/femnist', 'flwrlabs/ucf101', 'flwrlabs/ambient-acoustic-context', 'jlh/uci-mushrooms', 'Mike0307/MNIST-M', 'flwrlabs/usps', 'scikit-learn/iris', 'flwrlabs/pacs', 'flwrlabs/cinic10', 'flwrlabs/caltech101', 'flwrlabs/office-home', 'flwrlabs/fed-isic2019']. Given: jiahborcn/chembl_aqsol.
  warnings.warn(
Using: mps
OK, elapsed: 0.006102561950683594 s 741152.6875
load yaml path: configs/exp_ours.yaml
Traceback (most recent call last):
  File "/Users/yuandouwang/Documents/projects/flsim_min/flsim/run_experiment_ours.py", line 461, in <module>
    main()
  File "/Users/yuandouwang/Documents/projects/flsim_min/flsim/run_experiment_ours.py", line 206, in main
    Xp, yp, D, K, X_eval, y_eval = load_flower_arrays(
  File "/Users/yuandouwang/Documents/projects/flsim_min/flsim/data/flower.py", line 227, in load_flower_arrays
    ds = fds_train.load_partition(cid, split=split).with_format("numpy")
  File "/Users/yuandouwang/miniconda3/envs/FLSimulation/lib/python3.10/site-packages/flwr_datasets/federated_dataset.py", line 187, in load_partition
    partition = partitioner.load_partition(partition_id)
  File "/Users/yuandouwang/miniconda3/envs/FLSimulation/lib/python3.10/site-packages/flwr_datasets/partitioner/dirichlet_partitioner.py", line 134, in load_partition
    self._determine_partition_id_to_indices_if_needed()
  File "/Users/yuandouwang/miniconda3/envs/FLSimulation/lib/python3.10/site-packages/flwr_datasets/partitioner/dirichlet_partitioner.py", line 205, in _determine_partition_id_to_indices_if_needed
    self._unique_classes = self.dataset.unique(self._partition_by)
  File "/Users/yuandouwang/miniconda3/envs/FLSimulation/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 1850, in unique
    raise ValueError(f"Column ({column}) not in table columns ({self._data.column_names}).")
ValueError: Column (label) not in table columns (['smiles', 'logS', 'molecule_chembl_id', 'assay_description', 'MW', 'LogP', 'TPSA', 'Complexity']).
/Users/yuandouwang/miniconda3/envs/FLSimulation/lib/python3.10/site-packages/flwr_datasets/utils.py:109: UserWarning: The currently tested dataset are ['mnist', 'ylecun/mnist', 'cifar10', 'uoft-cs/cifar10', 'fashion_mnist', 'zalando-datasets/fashion_mnist', 'sasha/dog-food', 'zh-plus/tiny-imagenet', 'scikit-learn/adult-census-income', 'cifar100', 'uoft-cs/cifar100', 'svhn', 'ufldl-stanford/svhn', 'sentiment140', 'stanfordnlp/sentiment140', 'speech_commands', 'LIUM/tedlium', 'flwrlabs/femnist', 'flwrlabs/ucf101', 'flwrlabs/ambient-acoustic-context', 'jlh/uci-mushrooms', 'Mike0307/MNIST-M', 'flwrlabs/usps', 'scikit-learn/iris', 'flwrlabs/pacs', 'flwrlabs/cinic10', 'flwrlabs/caltech101', 'flwrlabs/office-home', 'flwrlabs/fed-isic2019']. Given: chembl_aqsol.
  warnings.warn(
Using: mps
OK, elapsed: 0.0028710365295410156 s 741525.0
load yaml path: configs/exp_ours.yaml
Traceback (most recent call last):
  File "/Users/yuandouwang/Documents/projects/flsim_min/flsim/run_experiment_ours.py", line 461, in <module>
    main()
  File "/Users/yuandouwang/Documents/projects/flsim_min/flsim/run_experiment_ours.py", line 206, in main
    Xp, yp, D, K, X_eval, y_eval = load_flower_arrays(
  File "/Users/yuandouwang/Documents/projects/flsim_min/flsim/data/flower.py", line 227, in load_flower_arrays
    ds = fds_train.load_partition(cid, split=split).with_format("numpy")
  File "/Users/yuandouwang/miniconda3/envs/FLSimulation/lib/python3.10/site-packages/flwr_datasets/federated_dataset.py", line 177, in load_partition
    self._prepare_dataset()
  File "/Users/yuandouwang/miniconda3/envs/FLSimulation/lib/python3.10/site-packages/flwr_datasets/federated_dataset.py", line 314, in _prepare_dataset
    self._dataset = datasets.load_dataset(
  File "/Users/yuandouwang/miniconda3/envs/FLSimulation/lib/python3.10/site-packages/datasets/load.py", line 2132, in load_dataset
    builder_instance = load_dataset_builder(
  File "/Users/yuandouwang/miniconda3/envs/FLSimulation/lib/python3.10/site-packages/datasets/load.py", line 1853, in load_dataset_builder
    dataset_module = dataset_module_factory(
  File "/Users/yuandouwang/miniconda3/envs/FLSimulation/lib/python3.10/site-packages/datasets/load.py", line 1717, in dataset_module_factory
    raise e1 from None
  File "/Users/yuandouwang/miniconda3/envs/FLSimulation/lib/python3.10/site-packages/datasets/load.py", line 1643, in dataset_module_factory
    raise DatasetNotFoundError(f"Dataset '{path}' doesn't exist on the Hub or cannot be accessed.") from e
datasets.exceptions.DatasetNotFoundError: Dataset 'chembl_aqsol' doesn't exist on the Hub or cannot be accessed.
